matrix:
  PYTHON_IMAGE:
    - continuumio/miniconda
    - continuumio/miniconda3

services:
  clickhouse:
    image: lensa/clickhouse

pipeline:
  test:
    image: ${PYTHON_IMAGE}
    environment:
      - CLICKHOUSE=http://clickhouse:8123
    commands:
      - conda install -y -q libgcc pandas numpy requests
      - python setup.py test
